# Generated by Django 4.1.3 on 2022-11-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook_data',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
