# Generated by Django 4.1.3 on 2022-11-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_rename_user_data_webhook_data_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhook_data',
            old_name='userid',
            new_name='user_data',
        ),
    ]
